transforms: [sentencepiece, prefix, suffix]
# nllb-200 specific prefixing and suffixing
src_prefix: "dyu_Latn"
tgt_prefix: "fra_Latn"
tgt_file_prefix: true
src_suffix: "</s>"
tgt_suffix: ""

#### Subword
src_subword_model: "/content/drive/MyDrive/zindi_opt/nmt/training/source.model"
tgt_subword_model: "/content/drive/MyDrive/zindi_opt/nmt/training/target.model"
src_subword_nbest: 1
src_subword_alpha: 0.0
tgt_subword_nbest: 1
tgt_subword_alpha: 0.0
# Model info
model: "/content/drive/MyDrive/zindi_opt/nmt/training/base_model/nllb-200-600M-onmt.pt"
# Inference
max_length: 120
gpu: 0
batch_type: tokens
batch_size: 8192
fp16:
beam_size: 1
report_time: true